[book]
authors = ["NeutronStarPRO"]
language = "en"
multilingual = false
src = "src"
title = "Constellation Book"
description = "The constellation book for you."

[rust]
edition = "2021"

[output.html]
additional-css = ["theme/style.css"]
additional-js = ["assets/custom.js", "assets/bigPicture.js"]
git-repository-url = "https://github.com/NeutronStarDAO/ConstellationBook-English"
mathjax-support = true

[output.html.playground]
editable = true
copy-js = true
# line-numbers = true

[output.html.fold]
enable = true
level = 0

